version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - "4466:4466"
    environment:
      LOG_LEVEL: TRACE
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: prismaDB
            database: ${MYSQL_DATABASE}
            rawAccess: true
            port: 3306
            user: root
            password: ${MYSQL_ROOT_PASSWORD}
    labels:
      - traefik.frontend.rule=Host:prisma.api.techinformi.localhost
      - traefik.enable=true
    networks:
      - techinformi-traefik_default
  prismaDB:
    image: mariadb:10.3.16
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - persistent:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - techinformi-traefik_default
  prismaPhpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    volumes:
      - ./upload.ini:/usr/local/etc/php/php.ini
    environment:
      PMA_HOST: prismaDB
    labels:
      - traefik.frontend.rule=Host:prisma.pma.techinformi.localhost
      - traefik.enable=true
    networks:
      - techinformi-traefik_default
  techinformi:
    image: alekoako2/techinformi
    labels:
      - traefik.frontend.rule=Host:techinformi.localhost
      - traefik.enable=true
    networks:
      - techinformi-traefik_default
networks:
  default:
    driver: bridge
  techinformi-traefik_default:
    external: true
volumes:
  persistent:
